### PR TITLE
Supporting PHP7

### PR DESCRIPTION
**Pull request by dlondero**
Hey @tomaszdurka here's a PR to drop support for PHP5 and add it for PHP 7.2+. Updated also `codegenerator` dependency.

Please let me know what you think!

### CODE REVIEW

**Comment by tomaszdurka** [comment]
Hey @dlondero are you still using this repo or its fork in any way?  Curious.

**Comment by dlondero** [comment]
Hey @tomaszdurka, yes we're still using our forks.

**Comment by tomaszdurka** [comment]
Thanks for reply. I guess you are ahead of this one already.
I don't have plans for the repo right now as I don't develop in php at all lately (could change). Would like to know if mocka is actually still a good/handy solution ? Or there are more interesting solutions, but you couldn't upgrade/migrate?

**Comment by dlondero** [comment]
Well it works, it is still handy. Thing is we periodically phase out unmaintained dependencies so we're not forced to work on tools used only by us.

**Pull request merged**
